version: '3.8'

services:
  mysql:
    image: mysql
    container_name: companydb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATABASE=compproanydb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=amaneiro7password
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

