version: '3.3'

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=compproanydb
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=avion01.
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

